module.exports = { 
    tha:{ 
        "from": "IDEM Info  <{email}>", 
        "subject": "Welcome to IDEM",  
        "body": "<div style='background-color: #ffffff; width: 100%;'><div style='width: 740px; margin-left: auto; margin-right: auto;'><p><br /><img style='text-align: center; display: block; margin-left: auto; margin-right: auto;'src='https://www.img.in.th/images/7f7c2fb9939baafd48c23fdbe95cfb08.png' alt='7f7c2fb9939baafd48c23fdbe95cfb08.png' border='0'><br /><br /></p><p style='padding-left:125px;text-align: left; font-weight: bold; font-size: 24px; line-height: 0px;color:#9AB94E;'>Hi {name}</p> <p style='padding-left:125px;text-align: left;color:#0D0D0D;'>Thanks for creating a AIS Partner account. with email {email} To complete email verification,please press the button below.</p><br/><div style='text-align: center;'><a style='color: #fff;text-decoration: none;' href='{link}' target='_blank'><button style='cursor: pointer;border: 1px solid transparent;width: 337px;height: 62px;font-size: 30px;color: #ffffff;background: linear-gradient(91.87deg, #A4CD39 0%, #4CE4C0 100%);box-shadow: 1px 2px 20px 3px rgba(0, 0, 0, 0.05);border-radius: 10px !important;'>Verify your Email</button></a></div><br><p style='padding-left:125px;text-align: left;color:#0D0D0D;'>Or verify using this link :<a href='{link}' target='_blank'>{link}</a></p><br><br><div style='background: linear-gradient(41deg, rgba(141,154,108,1) 0%, rgba(192,213,135,1) 49%, rgba(151,185,62,1) 100%);width: 740px;'><br><br><p style='text-align: center;padding-left:200px;padding-right:200px;'>if you did not sign up for this account you can ignore this email and the account will be deleted.</p><p style='text-align: center;'>Need help? Ask <a href='partnersupport@ais.co.th' target='_blank'>partnersupport@ais.co.th</a></p><br><br></div></div></div>"},
    eng:{ 
        "from": "IDEM Info  <{email}>",  
        "subject": "Welcome to IDEM",  
        "body": "<div style='background-color: #ffffff; width: 100%;'><div style='width: 740px; margin-left: auto; margin-right: auto;'><p><br /><img style='text-align: center; display: block; margin-left: auto; margin-right: auto;'src='https://www.img.in.th/images/7f7c2fb9939baafd48c23fdbe95cfb08.png' alt='7f7c2fb9939baafd48c23fdbe95cfb08.png' border='0'><br /><br /></p><p style='padding-left:125px;text-align: left; font-weight: bold; font-size: 24px; line-height: 0px;color:#9AB94E;'>Hi {name}</p> <p style='padding-left:125px;text-align: left;color:#0D0D0D;'>Thanks for creating a AIS Partner account. with email {email} To complete email verification,please press the button below.</p><br/><div style='text-align: center;'><a style='color: #fff;text-decoration: none;' href='{link}' target='_blank'><button style='cursor: pointer;border: 1px solid transparent;width: 337px;height: 62px;font-size: 30px;color: #ffffff;background: linear-gradient(91.87deg, #A4CD39 0%, #4CE4C0 100%);box-shadow: 1px 2px 20px 3px rgba(0, 0, 0, 0.05);border-radius: 10px !important;'>Verify your Email</button></a></div><br><p style='padding-left:125px;text-align: left;color:#0D0D0D;'>Or verify using this link :<a href='{link}' target='_blank'>{link}</a></p><br><br><div style='background: linear-gradient(41deg, rgba(141,154,108,1) 0%, rgba(192,213,135,1) 49%, rgba(151,185,62,1) 100%);width: 740px;'><br><br><p style='text-align: center;padding-left:200px;padding-right:200px;'>if you did not sign up for this account you can ignore this email and the account will be deleted.</p><p style='text-align: center;'>Need help? Ask <a href='partnersupport@ais.co.th' target='_blank'>partnersupport@ais.co.th</a></p><br><br></div></div></div>"}
}
